MONGODB_HOST: mongodb-{{ environment }}.daws90s.shop
REDIS_HOST: redis-{{ environment }}.daws90s.shop
MYSQL_HOST: mysql-{{ environment }}.daws90s.shop 
RABBITMQ_HOST: rabbitmq-{{ environment }}.daws90s.shop 
CATALOGUE_HOST: catalogue-{{ environment }}.daws90s.shop
USER_HOST: user-{{ environment }}.daws90s.shop
CART_HOST: cart-{{ environment }}.daws90s.shop
SHIPPING_HOST: shipping-{{ environment }}.daws90s.shop
PAYMENT_HOST: payment-{{ environment }}.daws90s.shop